module Onboardable
  class Error < StandardError
  end

  class UndefinedMethodError < Error
    def initialize: (Class klass, Symbol method) -> untyped
  end

  class StepConversionError < Error
    def initialize: (Class klass, Object step) -> untyped
  end

  class EmptyStepsError < Error
    def initialize: () -> untyped
  end

  class StepError < Error
    def initialize: (String step, Array[String] expected_steps) -> untyped
  end

  class ComparisonResultError < Error
    def initialize: (Integer comparison, Array[Integer] expected_comparisons) -> untyped
  end

  class LastStepError < Error
    def initialize: (String step, Array[String] expected_steps) -> untyped
  end

  class FirstStepError < Error
    def initialize: (String step, Array[String] expected_steps) -> untyped
  end

  class StepStatusError < Error
    def initialize: (Symbol status, Array[Symbol] expected_statuses) -> untyped
  end
end
