module Onboardable
  class List
    attr_reader steps: Array[Step]
    attr_reader current_step: Step

    def initialize: (Array[Step], Step) -> instance

    private

    attr_writer steps: Array[Step]
    attr_writer current_step: Step

    def step_index!: (Step)-> Integer
  end
end
