module Onboardable
  class List
    attr_reader steps: Array[Step]
    attr_reader current_step: Step

    def initialize: (Array[String], ?current_step: String?) -> instance

    private

    def steps=: (Array[String]) -> Array[Step]
    def current_step=: (Step) -> Step
  end
end
