module Onboardable
  class List
    attr_reader steps: Array[Step]
    attr_reader current_step: Step

    def initialize: (Array[Step], Step) -> instance

    def next_step: () -> Step
    def next_step!: () -> Step
    def prev_step: () -> Step
    def prev_step!: () -> Step
    def first_step?: () -> bool
    def last_step?: () -> bool

    private

    def steps=: (Array[Step]) -> Array[Step]
    def current_step=: (Step) -> Step

    def step_index!: (Step)-> Integer
  end
end
