module Onboardable
  class Step
    PENDING_STATUS: Symbol
    CURRENT_STATUS: Symbol
    COMPLETED_STATUS: Symbol
    DEFAULT_STATUS: Symbol
    STATUSES: Array[Symbol]

    attr_reader name: String
    attr_accessor status: Symbol
    attr_accessor representation: Class?

    def initialize: (String, Class?) -> instance

    def pending?: () -> bool
    def current?: () -> bool
    def completed?: () -> bool
    def ==: (Step) -> bool
    def to_s: () -> String
    def update_status!: (Integer) -> Symbol

    private

    def name=: (String) -> String
  end
end
