module Onboardable
  class StepsBuilder
    attr_reader steps: Array[String]

    def initialize: () -> instance

    def step=: (String, _class_representation: Class?) -> Array[String]
    alias step step=

    def build!: -> List
  end
end
