module Onboardable
  class Step
    PENDING_STATUS: Symbol
    CURRENT_STATUS: Symbol
    COMPLETED_STATUS: Symbol
    DEFAULT_STATUS: Symbol
    STATUSES: Array[Symbol]

    attr_reader name: String
    attr_reader status: Symbol

    def initialize: (String, ?status: Symbol) -> Step
    def pending?: () -> bool
    def current?: () -> bool
    def completed?: () -> bool
    def name=: (String) -> String
    def status=: (Symbol) -> Symbol
    def ==: (Step) -> bool
    def to_s: () -> String
    def update_status!: (Integer) -> Symbol
  end
end
