require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
