module Onboardable
  module Utils
    module Navigation
      def next_step: () -> Step?
      def next_step!: () -> Step
      def prev_step: () -> Step?
      def prev_step!: () -> Step
      def first_step?: () -> bool
      def last_step?: () -> bool
    end
  end
end
