module Onboardable
  module List
    class Base
      include Navigation

      PROGRESS_CALCULATION: untyped

      attr_reader steps: Array[Step]

      attr_reader current_step: Step

      def initialize: (Array[Step] steps, Step current_step, ?Hash[Symbol, untyped] options) -> untyped

      def progress: (?Proc? progress_calculation) -> Float

      private

      attr_reader options: Hash[Symbol, untyped]

      attr_writer steps: Array[Step]

      attr_writer current_step: Step

      attr_writer options: Hash[Symbol, untyped]

      def step_index: (Step step) -> Integer

      def update_each_step_status: (Integer current_step_index) -> Array[Step]

      def step_error!: (Step step) -> untyped
    end
  end
end
