module Onboardable
  module List
    class Base
      attr_reader steps: Array[Step]
      attr_reader current_step: Step

      def initialize: (Array[Step], Step) -> instance

      def progress: -> Float

      private

      attr_writer steps: Array[Step]
      attr_writer current_step: Step

      def step_index!: (Step)-> Integer
    end
  end
end
