module Onboardable
  module List
    class Builder
      attr_reader steps: Hash[String, Step]
      attr_accessor current_step: Step

      def initialize: () -> Hash[String, Step]

      def add_step: (String, Hash[Symbol, untyped]) -> Step
      alias step add_step

      def build!: (String?) -> Base

      private

      attr_writer steps: Hash[String, Step]

      def convert_to_step!: (String) -> Step

      def convert_to_steps!: -> Array[Step]
    end
  end
end
