module Onboardable
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides

  module ClassMethods
    attr_reader list_builder: ListBuilder

    def list_builder=: () { () -> ListBuilder } -> Step
    alias has_onboarding list_builder=
  end

  module InstanceMethods
    def  onboarding: (String?) -> List
  end
end
