module Onboardable
  VERSION: String

  def self.included: (Class klass) -> untyped

  module ClassMethods
    attr_accessor list_builder: List::Builder

    def onboarding=: (?Hash[Symbol, untyped] options) { () -> List::Builder } -> Step

    alias has_onboarding onboarding=

    def onboarding: (?String? current_step_name) -> List::Base
  end

  module InstanceMethods
    def onboarding: (?String? current_step_name) -> List::Base
  end
end
